### ISSUE TITLE
Couldn't setup with Next

### ISSUE THREAD

**Issue by eric-burel** [bitttttten/jest-transformer-mdx#11]
Hi,

I've tried to install 2.2.0 with Next, and I obtain this object when importing a .md as a component:
```js
import Readme from "../../../README.md";
console.log("readme", Readme);
// will print { process: [Function: createTransformer] } instead of a React component
```

Any idea where to begin to debug this? It feels like jest-transformer-mdx is not completely loaded or smth like that.

Using jest 26.

I can provide a repro if necessary, not really minimal though.

**Comment by eric-burel** [comment]
Dumb mistake, I was importing it in `moduleNameMapper` instead of `transform` so it behaved as an alias, replacing my import with the lib instead of parsing the file...$

Thanks for this lib, works so great!

**Comment by bitttttten** [comment]
Ah cool! I will update the readme to include instructions for next :) Are you on next 9.3?

**Comment by eric-burel** [comment]
I use the latest version, so 9.4.4 I think (it's an open source project: https://github.com/VulcanJS/vulcan-next-starter). I think the current docs are ok, it works the same way than in other JS app.

**Comment by bitttttten** [comment]
Great, then no action needed. Your vulcan next starter looks great btw, all the best!
